# Generated by Django 3.0 on 2019-12-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('X', models.DecimalField(decimal_places=15, help_text='Longitude', max_digits=20)),
                ('Y', models.DecimalField(decimal_places=15, help_text='Latitude', max_digits=20)),
                ('Unique_squirrel_ID', models.CharField(help_text='Hectare + Shift + Date + Hectare squirrel number', max_length=20, primary_key=True, serialize=False)),
                ('Hectare', models.CharField(help_text='ID tag', max_length=20)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='AM or PM', max_length=20)),
                ('Date', models.DateField(help_text='Date when squirrel was spotted')),
                ('Hectare_Squirrel_Number', models.IntegerField(help_text='Number of squirrel sightings')),
                ('Age', models.CharField(choices=[('ADULT', 'ADULT'), ('JUVENILE', 'JUVENILE')], help_text='Adult or Juvenile', max_length=20)),
                ('Primary_Fur_Color', models.CharField(choices=[('GRAY', 'GRAY'), ('CINAMMON', 'CINNAMON'), ('BLACK', 'BLACK')], help_text='gray, cinnamon or black', max_length=20)),
                ('Highlight_Fur_Color', models.CharField(help_text='Highlight color', max_length=20)),
                ('Combination_of_Color', models.CharField(help_text='Combination of primary and highlight fur color', max_length=20)),
                ('Color_Notes', models.CharField(help_text='Notes on color', max_length=20)),
                ('Location', models.CharField(choices=[('GROUND PLANE', 'GROUND PlANE'), ('ABOVE GROUND', 'ABOVE GROUND')], help_text='Ground plane or above ground', max_length=20)),
                ('Above_Ground_Sighter_Measurement', models.CharField(help_text='False if location is above ground', max_length=20)),
                ('Specific_Location', models.CharField(help_text='Comments on the squirrel location', max_length=20)),
                ('Running', models.BooleanField(help_text='True if squirrel was running')),
                ('Chasing', models.BooleanField(help_text='True if squirrel was chasing')),
                ('Climbing', models.BooleanField(help_text='True if squirrel was climbing')),
                ('Eating', models.BooleanField(help_text='True if squirrel was eating')),
                ('Foraging', models.BooleanField(help_text='True if squirrel was foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='Other activity by squirrel', max_length=20)),
                ('Kuks', models.BooleanField(default=False, help_text='Is  Squirrel kuking')),
                ('Quaas', models.BooleanField(default=False, help_text='Is  Squirrel quaaing')),
                ('Moans', models.BooleanField(default=False, help_text='Is Squirrel Moaning')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Is Squirrel flagging tail')),
                ('Tail_twitching', models.BooleanField(default=False, help_text='Is the Squirrel twitching tail')),
                ('Approaches', models.BooleanField(default=False, help_text='Is Squirrel approaching human')),
                ('Indifferent', models.BooleanField(default=False, help_text='Is squirrel indifferent to human')),
                ('Runs_from', models.BooleanField(default=False, help_text='Is Squirrel running from human')),
            ],
        ),
    ]
