# Generated by Django 3.0 on 2019-12-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0002_auto_20191207_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suquirrel',
            new_name='Squirrel',
        ),
    ]
