# Generated by Django 3.0 on 2019-12-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0004_auto_20191207_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('JUVENILE', 'JUVENILE')], help_text='Adult or Juvenile', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='True if squirrel was chasing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='True if squirrel was climbing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.IntegerField(blank=True, help_text='Date when squirrel was spotted', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='True if squirrel was eating'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='True if squirrel was foraging'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('GROUND PLANE', 'GROUND PlANE'), ('ABOVE GROUND', 'ABOVE GROUND')], help_text='Ground plane or above ground', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('GRAY', 'GRAY'), ('CINAMMON', 'CINNAMON'), ('BLACK', 'BLACK')], help_text='gray, cinnamon or black', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='True if squirrel was running'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='AM or PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Comments on the squirrel location', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Longitude', max_digits=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Latitude', max_digits=20),
        ),
    ]
